# Generated by Django 5.1.2 on 2024-10-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='approved',
        ),
    ]
