# Generated by Django 5.1.2 on 2024-10-25 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_students_course_enrollments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='overall_grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
