# Generated by Django 5.1.2 on 2024-10-23 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'ADMIN'), models.Q(('role', 'USER'), ('type', 'TEACHER')), _connector='OR'), max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='required_for', to='subjects.subject'),
        ),
    ]
