# Generated by Django 5.1.2 on 2024-10-25 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='number_credits',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
